// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/juju/juju/worker/peergrouper (interfaces: State,Machine)

// Package peergrouper is a generated GoMock package.
package peergrouper

import (
	gomock "github.com/golang/mock/gomock"
	controller "github.com/juju/juju/controller"
	network "github.com/juju/juju/network"
	state "github.com/juju/juju/state"
	status "github.com/juju/juju/status"
	reflect "reflect"
)

// MockState is a mock of State interface
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
}

// MockStateMockRecorder is the mock recorder for MockState
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// ControllerConfig mocks base method
func (m *MockState) ControllerConfig() (controller.Config, error) {
	ret := m.ctrl.Call(m, "ControllerConfig")
	ret0, _ := ret[0].(controller.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ControllerConfig indicates an expected call of ControllerConfig
func (mr *MockStateMockRecorder) ControllerConfig() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerConfig", reflect.TypeOf((*MockState)(nil).ControllerConfig))
}

// ControllerInfo mocks base method
func (m *MockState) ControllerInfo() (*state.ControllerInfo, error) {
	ret := m.ctrl.Call(m, "ControllerInfo")
	ret0, _ := ret[0].(*state.ControllerInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ControllerInfo indicates an expected call of ControllerInfo
func (mr *MockStateMockRecorder) ControllerInfo() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ControllerInfo", reflect.TypeOf((*MockState)(nil).ControllerInfo))
}

// Machine mocks base method
func (m *MockState) Machine(arg0 string) (Machine, error) {
	ret := m.ctrl.Call(m, "Machine", arg0)
	ret0, _ := ret[0].(Machine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Machine indicates an expected call of Machine
func (mr *MockStateMockRecorder) Machine(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Machine", reflect.TypeOf((*MockState)(nil).Machine), arg0)
}

// RemoveControllerMachine mocks base method
func (m *MockState) RemoveControllerMachine(arg0 Machine) error {
	ret := m.ctrl.Call(m, "RemoveControllerMachine", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveControllerMachine indicates an expected call of RemoveControllerMachine
func (mr *MockStateMockRecorder) RemoveControllerMachine(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveControllerMachine", reflect.TypeOf((*MockState)(nil).RemoveControllerMachine), arg0)
}

// WatchControllerConfig mocks base method
func (m *MockState) WatchControllerConfig() state.NotifyWatcher {
	ret := m.ctrl.Call(m, "WatchControllerConfig")
	ret0, _ := ret[0].(state.NotifyWatcher)
	return ret0
}

// WatchControllerConfig indicates an expected call of WatchControllerConfig
func (mr *MockStateMockRecorder) WatchControllerConfig() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchControllerConfig", reflect.TypeOf((*MockState)(nil).WatchControllerConfig))
}

// WatchControllerInfo mocks base method
func (m *MockState) WatchControllerInfo() state.NotifyWatcher {
	ret := m.ctrl.Call(m, "WatchControllerInfo")
	ret0, _ := ret[0].(state.NotifyWatcher)
	return ret0
}

// WatchControllerInfo indicates an expected call of WatchControllerInfo
func (mr *MockStateMockRecorder) WatchControllerInfo() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchControllerInfo", reflect.TypeOf((*MockState)(nil).WatchControllerInfo))
}

// WatchControllerStatusChanges mocks base method
func (m *MockState) WatchControllerStatusChanges() state.StringsWatcher {
	ret := m.ctrl.Call(m, "WatchControllerStatusChanges")
	ret0, _ := ret[0].(state.StringsWatcher)
	return ret0
}

// WatchControllerStatusChanges indicates an expected call of WatchControllerStatusChanges
func (mr *MockStateMockRecorder) WatchControllerStatusChanges() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchControllerStatusChanges", reflect.TypeOf((*MockState)(nil).WatchControllerStatusChanges))
}

// MockMachine is a mock of Machine interface
type MockMachine struct {
	ctrl     *gomock.Controller
	recorder *MockMachineMockRecorder
}

// MockMachineMockRecorder is the mock recorder for MockMachine
type MockMachineMockRecorder struct {
	mock *MockMachine
}

// NewMockMachine creates a new mock instance
func NewMockMachine(ctrl *gomock.Controller) *MockMachine {
	mock := &MockMachine{ctrl: ctrl}
	mock.recorder = &MockMachineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMachine) EXPECT() *MockMachineMockRecorder {
	return m.recorder
}

// Addresses mocks base method
func (m *MockMachine) Addresses() []network.Address {
	ret := m.ctrl.Call(m, "Addresses")
	ret0, _ := ret[0].([]network.Address)
	return ret0
}

// Addresses indicates an expected call of Addresses
func (mr *MockMachineMockRecorder) Addresses() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Addresses", reflect.TypeOf((*MockMachine)(nil).Addresses))
}

// HasVote mocks base method
func (m *MockMachine) HasVote() bool {
	ret := m.ctrl.Call(m, "HasVote")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasVote indicates an expected call of HasVote
func (mr *MockMachineMockRecorder) HasVote() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasVote", reflect.TypeOf((*MockMachine)(nil).HasVote))
}

// Id mocks base method
func (m *MockMachine) Id() string {
	ret := m.ctrl.Call(m, "Id")
	ret0, _ := ret[0].(string)
	return ret0
}

// Id indicates an expected call of Id
func (mr *MockMachineMockRecorder) Id() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Id", reflect.TypeOf((*MockMachine)(nil).Id))
}

// Life mocks base method
func (m *MockMachine) Life() state.Life {
	ret := m.ctrl.Call(m, "Life")
	ret0, _ := ret[0].(state.Life)
	return ret0
}

// Life indicates an expected call of Life
func (mr *MockMachineMockRecorder) Life() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Life", reflect.TypeOf((*MockMachine)(nil).Life))
}

// Refresh mocks base method
func (m *MockMachine) Refresh() error {
	ret := m.ctrl.Call(m, "Refresh")
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh
func (mr *MockMachineMockRecorder) Refresh() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockMachine)(nil).Refresh))
}

// SetHasVote mocks base method
func (m *MockMachine) SetHasVote(arg0 bool) error {
	ret := m.ctrl.Call(m, "SetHasVote", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHasVote indicates an expected call of SetHasVote
func (mr *MockMachineMockRecorder) SetHasVote(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHasVote", reflect.TypeOf((*MockMachine)(nil).SetHasVote), arg0)
}

// SetStatus mocks base method
func (m *MockMachine) SetStatus(arg0 status.StatusInfo) error {
	ret := m.ctrl.Call(m, "SetStatus", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetStatus indicates an expected call of SetStatus
func (mr *MockMachineMockRecorder) SetStatus(arg0 interface{}) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockMachine)(nil).SetStatus), arg0)
}

// Status mocks base method
func (m *MockMachine) Status() (status.StatusInfo, error) {
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(status.StatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Status indicates an expected call of Status
func (mr *MockMachineMockRecorder) Status() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockMachine)(nil).Status))
}

// WantsVote mocks base method
func (m *MockMachine) WantsVote() bool {
	ret := m.ctrl.Call(m, "WantsVote")
	ret0, _ := ret[0].(bool)
	return ret0
}

// WantsVote indicates an expected call of WantsVote
func (mr *MockMachineMockRecorder) WantsVote() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WantsVote", reflect.TypeOf((*MockMachine)(nil).WantsVote))
}

// Watch mocks base method
func (m *MockMachine) Watch() state.NotifyWatcher {
	ret := m.ctrl.Call(m, "Watch")
	ret0, _ := ret[0].(state.NotifyWatcher)
	return ret0
}

// Watch indicates an expected call of Watch
func (mr *MockMachineMockRecorder) Watch() *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockMachine)(nil).Watch))
}
